# Generated by Django 5.2.4 on 2026-02-18 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_delete_todoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
